name: 🏗 Build on CI

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Taskfile
        run: brew install go-task

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          target: 'x86_64-apple-darwin'

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: task build-universal

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: swift-precompiler
          path: target/swift-precompiler

      - name: Publish
        # https://doc.rust-lang.org/cargo/reference/config.html?highlight=CARGO_REGISTRY_TOKEN#credentials
        env:
          CARGO_REGISTRY_TOKEN: "${{ secrets.CARGO_REGISTRY_TOKEN }}"
        run: |
          cargo publish --locked